### PR TITLE
add log for remote actors

### PR DESCRIPTION
**Pull request by lsc-winter**

### CODE REVIEW

**Comment by TomorrowIsAnOtherDay** [comment]
Thanks a lot!  Is this PR related to #212 ?
We are happy that you are willing to improve PARL, but what we want to address is to provide the log path of remote actors in Web UI, so that users can check the log and find the problem in remote actors. 
We are sorry for not describing the issue in detail.

**Comment by lsc-winter** [comment]
> Thanks a lot! Is this PR related to #212 ?
> We are happy that you are willing to improve PARL, but what we want to address is to provide the log path of remote actors in Web UI, so that users can check the log and find the problem in remote actors.
> We are sorry for not describing the issue in detail.

I am sorry for misunderstanding the question,do you mean that client can see not only the log path but also log files of the remote workers in the web. Because i just have saw the files under parl/remote,is it passible to change codes to solve the question in just this files?

**Comment by TomorrowIsAnOtherDay** [comment]
Exactly. We tend to display the log of remote actors on Web UI. It needs some change on the front-end code, as it must load the log on the disk, and display it on Web UI.

**Comment by TomorrowIsAnOtherDay** [comment]
We are closing this PR as #269 has implemented this feature.

**Pull request closed without merging**
