### PR TITLE
redirect stderr of subprocesses to console output

### PR DESCRIPTION
**Pull request by zenghsh3**
After this PR, the stderr of subprocesses(starting the master/worker/job) will be redirected to the console output.

### CODE REVIEW

**Comment by zenghsh3** [comment]
image

**Comment by zenghsh3** [comment]
image

**Comment by TomorrowIsAnOtherDay** [comment]
Please add the log telling user that the log_server runs successfully.

**Comment by zenghsh3** [comment]
> Please add the log telling user that the log_server runs successfully.

fixed

**Pull request closed without merging**
