### PR TITLE
Fix remote actor using gpu

### PR DESCRIPTION
**Pull request by zenghsh3**

### CODE REVIEW

**Review by TomorrowIsAnOtherDay — DISMISSED** [review]
LGTM.

**Comment by TomorrowIsAnOtherDay** [comment]
Deep learning frameworks like Torch cache the GPU status for the first time that `is_gpu_available()` is called. This PR disables using GPU by default. 
Users can still use GPU by resetting the environment variable: `export CUDA_VISIBLE_DEVICES=0,1` in their implementation of actors.

**Comment by zenghsh3** [comment]
> Deep learning frameworks like Torch cache the GPU status for the first time that `is_gpu_available()` is called. This PR disables using GPU by default.
> Users can still use GPU by resetting the environment variable: `export CUDA_VISIBLE_DEVICES=0,1` in their implementation of actors.

fixed

**Review by TomorrowIsAnOtherDay — APPROVED** [review]
Great.

**Pull request merged**
